import { getServerSession } from "next-auth";
import { authOptions } from "@/auth";
import { getTenantClientFromSession } from "@/lib/tenant";
import { formatBDT } from "@/lib/format";
export default async function ExpensesPage(){
  const session=await getServerSession(authOptions);
  const prisma:any=await getTenantClientFromSession();
  const projects=await prisma.landProject.findMany();
  const partners=await prisma.partner.findMany();
  const banks=await prisma.bankAccount.findMany();
  const expenses=await prisma.projectExpense.findMany({orderBy:{createdAt:"desc"}});
  const pending=expenses.filter((e:any)=>e.status==="PENDING");
  // cost breakdown
  const breakdown:any={}; expenses.filter((e:any)=>e.status==="APPROVED").forEach((e:any)=>{ const k=e.projectId||"General"; breakdown[k]=(breakdown[k]||0)+Number(e.amount); });
  return (<div className="p-6 space-y-6">
    <h1 className="text-2xl font-bold">Expenses</h1>
    <form action="/api/expenses" method="post" encType="multipart/form-data" className="bg-white p-4 rounded-xl shadow border grid grid-cols-2 gap-3">
      <select name="project_id" className="border rounded px-3 py-2"><option value="">No Project</option>{projects.map((p:any)=><option key={p.id} value={p.id}>{p.projectName}</option>)}</select>
      <input name="category" placeholder="Category" required className="border rounded px-3 py-2"/>
      <input name="amount" type="number" step="0.01" placeholder="Amount" required className="border rounded px-3 py-2"/>
      <select name="payment_channel" className="border rounded px-3 py-2"><option>CASH</option><option>BANK</option><option>PAID_BY_PARTNER</option></select>
      <select name="bank_account" className="border rounded px-3 py-2"><option value="">Bank Account</option>{banks.map((b:any)=><option key={b.id} value={b.id}>{b.bankName}-{b.accountNumber}</option>)}</select>
      <select name="paid_by_partner" className="border rounded px-3 py-2"><option value="">Paid By Partner</option>{partners.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
      <input name="voucher" type="file" className="border rounded px-3 py-2"/>
      <input name="description" placeholder="Description" className="border rounded px-3 py-2 col-span-2"/>
      <button formAction={async(formData:FormData)=>{"use server"; const {getTenantClientFromSession}=await import("@/lib/tenant"); const {storage}=await import("@/lib/storage"); const {writeAudit,isPaidByPartner}=await import("@/lib/tenantRules"); const {getServerSession}=await import("next-auth"); const {authOptions}=await import("@/auth"); const {randomUUID}=await import("crypto"); const {revalidatePath}=await import("next/cache"); const s=await getServerSession(authOptions); const prisma:any=await getTenantClientFromSession(); const amt=parseFloat(formData.get("amount") as string); const ch=formData.get("payment_channel") as string; let url=null; const f=formData.get("voucher") as any; if(f&&f.size){ const buf=Buffer.from(await f.arrayBuffer()); url=await storage.save(`vouchers/${randomUUID()}-${f.name}`,buf);} const id=randomUUID(); await prisma.$transaction(async(tx:any)=>{ const e=await tx.projectExpense.create({data:{id,projectId:(formData.get("project_id") as string)||null,expenseCategory:formData.get("category") as string,amount:amt,expenseDate:new Date(),description:formData.get("description") as string,paymentChannel:ch,bankAccountId:ch==="BANK"?formData.get("bank_account") as string:null,paidByPartnerId:isPaidByPartner(ch)?formData.get("paid_by_partner") as string:null,voucherImageUrl:url,status:"PENDING",createdBy:(s!.user as any).id}}); await writeAudit(tx,"project_expenses",id,"CREATE",(s!.user as any).id,null,e);}); revalidatePath("/expenses");}} className="bg-blue-600 text-white rounded px-4 py-2 col-span-2">Create Expense</button>
    </form>
    <h2 className="font-semibold">Approval Queue (PENDING)</h2>
    <table className="w-full text-sm bg-white rounded-xl shadow border"><thead><tr className="border-b"><th className="p-2">Category</th><th>Amount</th><th>Channel</th><th>Status</th><th>Action</th></tr></thead><tbody>{pending.map((e:any)=><tr key={e.id} className="border-b"><td className="p-2">{e.expenseCategory}</td><td>{formatBDT(Number(e.amount))}</td><td>{e.paymentChannel}</td><td>{e.status}</td><td><form><button formAction={async()=>{"use server"; const s=await (await import("next-auth")).getServerSession((await import("@/auth")).authOptions); const p:any=await (await import("@/lib/tenant")).getTenantClientFromSession(); const {writeAudit,isPaidByPartner}=await import("@/lib/tenantRules"); const {can}=await import("@/lib/rbac"); if(!can((s!.user as any).role,"approveExpense")) throw new Error("Forbidden"); const {randomUUID}=await import("crypto"); await p.$transaction(async(tx:any)=>{ const exp=await tx.projectExpense.findUnique({where:{id:e.id}}); const upd=await tx.projectExpense.update({where:{id:e.id},data:{status:"APPROVED",approvedBy:(s!.user as any).id}}); await writeAudit(tx,"project_expenses",e.id,"UPDATE",(s!.user as any).id,exp,upd); if(isPaidByPartner(exp.paymentChannel)){ const pt=await tx.partnerTransaction.create({data:{id:randomUUID(),partnerId:exp.paidByPartnerId,txnType:"DIRECT_EXPENSE",amount:exp.amount,txnDate:new Date(),referenceId:e.id}}); await writeAudit(tx,"partner_transactions",pt.id,"CREATE",(s!.user as any).id,null,pt);} else { const tl=await tx.treasuryLedger.create({data:{id:randomUUID(),txnDate:new Date(),accountType:exp.paymentChannel==="BANK"?"BANK":"CASH",bankAccountId:exp.bankAccountId,flowType:"OUT",amount:exp.amount,purpose:exp.expenseCategory,referenceType:"EXPENSE",referenceId:e.id,createdBy:(s!.user as any).id}}); await writeAudit(tx,"treasury_ledger",tl.id,"CREATE",(s!.user as any).id,null,tl);} }); const {revalidatePath}=await import("next/cache"); revalidatePath("/expenses");}} className="bg-green-600 text-white px-2 py-1 rounded mr-1">Approve</button><button formAction={async()=>{"use server"; const s=await (await import("next-auth")).getServerSession((await import("@/auth")).authOptions); const p:any=await (await import("@/lib/tenant")).getTenantClientFromSession(); const {writeAudit}=await import("@/lib/tenantRules"); await p.$transaction(async(tx:any)=>{ const exp=await tx.projectExpense.findUnique({where:{id:e.id}}); const upd=await tx.projectExpense.update({where:{id:e.id},data:{status:"REJECTED",approvedBy:(s!.user as any).id}}); await writeAudit(tx,"project_expenses",e.id,"UPDATE",(s!.user as any).id,exp,upd);}); const {revalidatePath}=await import("next/cache"); revalidatePath("/expenses");}} className="bg-red-600 text-white px-2 py-1 rounded">Reject</button></form></td></tr>)}</tbody></table>
    <h2 className="font-semibold">Project-wise Cost Breakdown</h2>
    <table className="w-full text-sm bg-white rounded-xl shadow border"><thead><tr className="border-b"><th className="p-2">Project</th><th>Total Cost</th></tr></thead><tbody>{Object.entries(breakdown).map(([k,v]:any)=><tr key={k} className="border-b"><td className="p-2">{projects.find((p:any)=>p.id===k)?.projectName||k}</td><td>{formatBDT(Number(v))}</td></tr>)}</tbody></table>
  </div>);
}
